name: windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Enable core dumps
        run: ulimit -c unlimited
        shell: bash

      - uses: actions/checkout@v3

      - name: Install prerequisites
        run: |
          choco install -y cmake git make mingw
          refreshenv

      - name: Install GDB with MinGW
        run: |
          choco install mingw --version=13.2.0
          refreshenv
          setx PATH "%PATH%;C:\tools\mingw64\bin"
          mingw-get install gdb
        shell: cmd

      - name: Install PostgreSQL
        run: |
          choco install -y postgresql
          refreshenv

      - name: Start PostgreSQL service
        run: |
          net start postgresql-x64-14

      - name: Configure PostgreSQL
        run: |
          "C:\Program Files\PostgreSQL\14\bin\psql.exe" -U postgres -c "CREATE DATABASE my_db;"
          "C:\Program Files\PostgreSQL\14\bin\psql.exe" -U postgres -c "CREATE USER my_user WITH PASSWORD 'my_password';"
          "C:\Program Files\PostgreSQL\14\bin\psql.exe" -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE my_db TO my_user;"
          "C:\Program Files\PostgreSQL\14\bin\psql.exe" -U postgres -d my_db -c "CREATE TABLE my_table (id SERIAL PRIMARY KEY, description TEXT);"

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
          C:\vcpkg\bootstrap-vcpkg.bat
          setx PATH "%PATH%;C:\vcpkg"

      - name: Clone project repository
        run: |
          git clone https://github.com/leventkaragol/libcpp-pg-pool.git C:\libcpp-pg-pool

      - name: Run cmake with vcpkg toolchain
        run: |
          cd C:\libcpp-pg-pool
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake
        shell: cmd

      - name: Build the project
        run: |
          cd C:\libcpp-pg-pool
          cmake --build build --config Release
        shell: cmd

      - name: Run tests with gdb
        run: |
          cd C:\libcpp-pg-pool
          gdb -ex "run" -ex "bt" -ex "quit" --args build\test\test.exe
        shell: bash
